name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["Type: Bug"]
assignees:
  - CheeseTastisch
body:
  - type: markdown
    attributes:
      value: "# General"
  - type: textarea
    id: describiton
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshotes
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false
  - type: markdown
    attributes:
      value: "# Versions and extentions"
  - type: dropdown
    id: version
    attributes:
      label: Minecraft Version
      description: On witch minecraft version did the bug occur?
      options:
        - 1.19.3
        - 1.19.2
        - 1.19.1
        - 1.19
        - Other (siehe below)
        - Snapshot (siehe below)
    validations:
      required: true
  - type: input
    id: other_version
    attributes:
      label: Other Version
      description: If other or snapshot version is selected, witch versions?
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operation System
      description: On witch operation system did the bug occur?
    validations:
      required: true
  - type: input
    id: extentions
    attributes:
      label: Extentions
      description: Witch extentions (mods, texturepacks, etc.) where installed.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "# Additional"
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false
